### ISSUE TITLE
Ninja build third_party/spirv-tools/source/libSPIRV-Tools.a No such file or directory

### ISSUE THREAD

**Issue by chakmeshma** [google/shaderc#406] opened 2017-11-25 10:19 UTC
I'm getting this error towards the end of ninja make:
```
[177/185] Linking CXX executable third_party\glslang\StandAlone\spirv-remap.exe
FAILED: third_party/glslang/StandAlone/spirv-remap.exe
cmd.exe /C "cd . && C:\dev\msys64\mingw64\bin\c++.exe   -static -static-libgcc -static-libstdc++ third_party/glslang/StandAlone/CMakeFiles/spirv-remap.dir/spirv-remap.cpp.obj  -o third_party\glslang\StandAlone\spirv-remap.exe -Wl,--out-implib,third_party\glslang\StandAlone\libspirv-remap.dll.a -Wl,--major-image-version,0,--minor-image-version,0  third_party/glslang/glslang/libglslang.a third_party/glslang/SPIRV/libSPIRV.a third_party/glslang/SPIRV/libSPVRemapper.a third_party/glslang/StandAlone/libglslang-default-resource-limits.a -lpsapi third_party/glslang/glslang/libglslang.a third_party/glslang/OGLCompilersDLL/libOGLCompiler.a third_party/glslang/glslang/OSDependent/Windows/libOSDependent.a third_party/glslang/hlsl/libHLSL.a third_party/spirv-tools/source/opt/libSPIRV-Tools-opt.a third_party/spirv-tools/source/libSPIRV-Tools.a -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
c++.exe: error: third_party/spirv-tools/source/opt/libSPIRV-Tools-opt.a: No such file or directory
c++.exe: error: third_party/spirv-tools/source/libSPIRV-Tools.a: No such file or directory
[178/185] Linking CXX executable third_party\glslang\StandAlone\glslangValidator.exe
FAILED: third_party/glslang/StandAlone/glslangValidator.exe
cmd.exe /C "cd . && C:\dev\msys64\mingw64\bin\c++.exe   -static -static-libgcc -static-libstdc++ third_party/glslang/StandAlone/CMakeFiles/glslangValidator.dir/StandAlone.cpp.obj  -o third_party\glslang\StandAlone\glslangValidator.exe -Wl,--out-implib,third_party\glslang\StandAlone\libglslangValidator.dll.a -Wl,--major-image-version,0,--minor-image-version,0  third_party/glslang/glslang/libglslang.a third_party/glslang/SPIRV/libSPIRV.a third_party/glslang/SPIRV/libSPVRemapper.a third_party/glslang/StandAlone/libglslang-default-resource-limits.a -lpsapi third_party/glslang/glslang/libglslang.a third_party/glslang/OGLCompilersDLL/libOGLCompiler.a third_party/glslang/glslang/OSDependent/Windows/libOSDependent.a third_party/glslang/hlsl/libHLSL.a third_party/spirv-tools/source/opt/libSPIRV-Tools-opt.a third_party/spirv-tools/source/libSPIRV-Tools.a -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
c++.exe: error: third_party/spirv-tools/source/opt/libSPIRV-Tools-opt.a: No such file or directory
c++.exe: error: third_party/spirv-tools/source/libSPIRV-Tools.a: No such file or directory
[179/185] Linking CXX static library libshaderc_util\libshaderc_util.a
ninja: build stopped: subcommand failed.
```

**Comment by dneto0** [comment] 2017-11-30 16:38
I don't have enough information to help you.  I would try verifying that the source tree is configured correctly.

**Comment by DanOlivier** [comment] 2018-02-20 00:33
I'm getting the same thing now on ubuntu 17.10:

```shell
git clone https://github.com/google/shaderc.git -b known-good --single-branch
cd shaderc
./update_shaderc_sources.py
mkdir build && cd build 
cmake ../src -G Ninja -DSPIRV_SKIP_TESTS=ON
ninja
```
I also tried building in-tree (not out-of-source), and without Ninja, all with the same, final, effect.

Here is my output:
```shell
2081 Zelos2 λ  (~/tools/nvidia)
 $ git clone https://github.com/google/shaderc.git -b known-good --single-branch
Cloning into 'shaderc'...
remote: Counting objects: 89, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 89 (delta 2), reused 3 (delta 1), pack-reused 83
Unpacking objects: 100% (89/89), done.

2082 Zelos2 λ  (~/tools/nvidia)
 $ cd shaderc/

2082 Zelos2 λ  (~/tools/nvidia/shaderc 8a60ff4 known-good✓)
 $ ./update_shaderc_sources.py
Change directory to src
Get shaderc

In .: ['git', 'clone', 'https://github.com/google/shaderc', '.']
Cloning into '.'...
remote: Counting objects: 3154, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 3154 (delta 2), reused 3 (delta 1), pack-reused 3148
Receiving objects: 100% (3154/3154), 988.76 KiB | 5.49 MiB/s, done.
Resolving deltas: 100% (2113/2113), done.

In .: ['git', 'remote', 'get-url', 'known-good']
fatal: No such remote 'known-good'

In .: ['git', 'remote', 'add', 'known-good', 'https://github.com/google/shaderc']

563bc6e87a43c38b5495469307922c768edbd191
In .: ['git', 'checkout', u'563bc6e87a43c38b5495469307922c768edbd191']
Note: checking out '563bc6e87a43c38b5495469307922c768edbd191'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 563bc6e... Add a virtual destructor, otherwise Clang 6.0complains about delete being called on an abstract class.

Get glslang

In third_party/glslang: ['git', 'clone', 'https://github.com/KhronosGroup/glslang', '.']
Cloning into '.'...
remote: Counting objects: 30508, done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 30508 (delta 10), reused 15 (delta 9), pack-reused 30479
Receiving objects: 100% (30508/30508), 39.89 MiB | 6.07 MiB/s, done.
Resolving deltas: 100% (25707/25707), done.

In third_party/glslang: ['git', 'remote', 'get-url', 'known-good']
fatal: No such remote 'known-good'

In third_party/glslang: ['git', 'remote', 'add', 'known-good', 'https://github.com/KhronosGroup/glslang']

23ea3db3e5ea16b4964e9e3b5fee88bfc267fc57
In third_party/glslang: ['git', 'checkout', u'23ea3db3e5ea16b4964e9e3b5fee88bfc267fc57']
Note: checking out '23ea3db3e5ea16b4964e9e3b5fee88bfc267fc57'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 23ea3db3... Warning for #pragma once. GLSL and HLSL. Addresses #824.

Get googletest

In third_party/googletest: ['git', 'clone', 'https://github.com/google/googletest', '.']
Cloning into '.'...
remote: Counting objects: 10384, done.
remote: Total 10384 (delta 0), reused 0 (delta 0), pack-reused 10384
Receiving objects: 100% (10384/10384), 3.06 MiB | 6.01 MiB/s, done.
Resolving deltas: 100% (7661/7661), done.

In third_party/googletest: ['git', 'remote', 'get-url', 'known-good']
fatal: No such remote 'known-good'

In third_party/googletest: ['git', 'remote', 'add', 'known-good', 'https://github.com/google/googletest']

a3c73ed28d7995b18d48027aee740ad827fcc157
In third_party/googletest: ['git', 'checkout', u'a3c73ed28d7995b18d48027aee740ad827fcc157']
Note: checking out 'a3c73ed28d7995b18d48027aee740ad827fcc157'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at a3c73ed... Include MSVC14 on PRs as well

Get spirv-tools

In third_party/spirv-tools: ['git', 'clone', 'https://github.com/KhronosGroup/SPIRV-Tools', '.']
Cloning into '.'...
remote: Counting objects: 12048, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 12048 (delta 8), reused 2 (delta 2), pack-reused 12035
Receiving objects: 100% (12048/12048), 6.45 MiB | 6.07 MiB/s, done.
Resolving deltas: 100% (8916/8916), done.

In third_party/spirv-tools: ['git', 'remote', 'get-url', 'known-good']
fatal: No such remote 'known-good'

In third_party/spirv-tools: ['git', 'remote', 'add', 'known-good', 'https://github.com/KhronosGroup/SPIRV-Tools']

5d442fad2f00fcca8354aaaa9bfd36be8c418a1b
In third_party/spirv-tools: ['git', 'checkout', u'5d442fad2f00fcca8354aaaa9bfd36be8c418a1b']
Note: checking out '5d442fad2f00fcca8354aaaa9bfd36be8c418a1b'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 5d442fa... fix typo

Get spirv-headers

In third_party/spirv-tools/external/spirv-headers: ['git', 'clone', 'https://github.com/KhronosGroup/SPIRV-Headers', '.']
Cloning into '.'...
remote: Counting objects: 631, done.
remote: Total 631 (delta 0), reused 0 (delta 0), pack-reused 631
Receiving objects: 100% (631/631), 344.22 KiB | 4.36 MiB/s, done.
Resolving deltas: 100% (397/397), done.

In third_party/spirv-tools/external/spirv-headers: ['git', 'remote', 'get-url', 'known-good']
fatal: No such remote 'known-good'

In third_party/spirv-tools/external/spirv-headers: ['git', 'remote', 'add', 'known-good', 'https://github.com/KhronosGroup/SPIRV-Headers']

ce309203d7eceaf908bea8862c27f3e0749f7d00
In third_party/spirv-tools/external/spirv-headers: ['git', 'checkout', u'ce309203d7eceaf908bea8862c27f3e0749f7d00']
Note: checking out 'ce309203d7eceaf908bea8862c27f3e0749f7d00'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at ce30920... BuildHeaders: Add missing 'const'.


2082 Zelos2 λ  (~/tools/nvidia/shaderc 8a60ff4 known-good✓)
 $ mkcd build

2082 Zelos2 λ  (~/tools/nvidia/shaderc/build 8a60ff4 known-good✓)
 $ cmake ../src -G Ninja -DSPIRV_SKIP_TESTS=ON
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Shaderc: build type is "".
-- Configuring Shaderc to build tests.
-- asciidoctor was not found - no documentation will be generated
-- Found PythonInterp: /usr/bin/python (found version "2.7.14")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- No build type selected, default to Debug
-- Google Mock already configured - use it
-- optimizer enabled
-- Google Mock found - building tests
-- Configuring done
-- Generating done
CMake Warning (dev):
  Policy CMP0058 is not set: Ninja requires custom command byproducts to be
  explicit.  Run "cmake --help-policy CMP0058" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  This project specifies custom command DEPENDS on files in the build tree
  that are not specified as the OUTPUT or BYPRODUCTS of any
  add_custom_command or add_custom_target:

   third_party/spirv-tools/source/libSPIRV-Tools.a
   third_party/spirv-tools/source/opt/libSPIRV-Tools-opt.a

  For compatibility with versions of CMake that did not have the BYPRODUCTS
  option, CMake is generating phony rules for such files to convince 'ninja'
  to build.

  Project authors should add the missing BYPRODUCTS or OUTPUT options to the
  custom commands that produce these files.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Build files have been written to: /home/daniel/tools/nvidia/shaderc/build

2082 Zelos2 λ  (~/tools/nvidia/shaderc/build 8a60ff4 known-good✓)
 $ ninja
[302/363] Linking CXX executable third_party/glslang/StandAlone/glslangValidator
FAILED: third_party/glslang/StandAlone/glslangValidator
: && /usr/bin/c++    -rdynamic third_party/glslang/StandAlone/CMakeFiles/glslangValidator.dir/StandAlone.cpp.o  -o third_party/glslang/StandAlone/glslangValidator  third_party/glslang/glslang/libglslang.a third_party/glslang/SPIRV/libSPIRV.a third_party/glslang/SPIRV/libSPVRemapper.a third_party/glslang/StandAlone/libglslang-default-resource-limits.a -lpthread third_party/glslang/glslang/libglslang.a third_party/glslang/OGLCompilersDLL/libOGLCompiler.a third_party/glslang/glslang/OSDependent/Unix/libOSDependent.a third_party/glslang/hlsl/libHLSL.a third_party/spirv-tools/source/opt/libSPIRV-Tools-opt.a third_party/spirv-tools/source/libSPIRV-Tools.a && :
c++: error: third_party/spirv-tools/source/opt/libSPIRV-Tools-opt.a: No such file or directory
c++: error: third_party/spirv-tools/source/libSPIRV-Tools.a: No such file or directory
[311/363] Building CXX object libshaderc_util/CMakeFiles/shaderc_util_compiler_test.dir/src/compiler_test.cc.o
ninja: build stopped: subcommand failed.
```

**Comment by DanOlivier** [comment] 2018-02-20 01:55
In my case, the missing libraries from SPIRV-Tools were being built with a `'d'` suffix, caused by the following line in `third_party/googletest/googletest/CMakeLists.txt`:
```
set(CMAKE_DEBUG_POSTFIX "d" CACHE STRING "Generate debug library name with a postfix.")
```
`googletest` is included from `third_party/spirv-tools/CMakeLists.txt` (using `add_subdirectory(external)`), which includes `third_party/spirv-tools/external/CMakeLists.txt`, which itself includes `gmock` with `add_subdirectory(${GMOCK_DIR} EXCLUDE_FROM_ALL)`.

`gmock` will then boostrap `gtest` by looking for it in its parent directory.

However, I'm surprised that the included third-party build file (gtest, gmock) is allowed to alter this _global setting_ (CMAKE_DEBUG_POSTFIX), and impact the target generation for all targets that follow.

Perhaps relevant: [CMake: How to build external projects and include their targets](https://stackoverflow.com/questions/15175318/cmake-how-to-build-external-projects-and-include-their-targets)

**Comment by dneto0** [comment] 2018-02-26 19:50
@DanOlivier  Thanks.  This helps a lot.

**Comment by dneto0** [comment] 2018-02-26 21:05
I've posted a fix to Googletest
https://github.com/google/googletest/pull/1481

**Comment by dneto0** [comment] 2018-02-28 15:20
Fixed by this update to the known-good branch: 
https://github.com/google/shaderc/commit/a481333851d661e75897b01cef11d9c142124442

**Closed by dneto0** 2018-02-28 15:20 UTC
