### ISSUE TITLE
shaderc.h includes libshaderc_util headers, which are not installed (CMake)

### ISSUE THREAD

**Issue by Akaricchi** [google/shaderc#551] opened 2019-01-24 23:15 UTC

**Comment by Themaister** [comment] 2019-01-28 20:18
Also seeing this issue when building shaderc as a library:
```
In file included from /home/maister/git/granite/third_party/shaderc/libshaderc/include/shaderc/shaderc.hpp:22,
                 from /home/maister/git/granite/compiler/compiler.cpp:24:
/home/maister/git/granite/third_party/shaderc/libshaderc/include/shaderc/shaderc.h:26:10: fatal error: libshaderc_util/common.h: No such file or directory
 #include "libshaderc_util/common.h"
```

**Comment by dneto0** [comment] 2019-01-29 00:43
I see it wasn't entirely clear that the entire libshaderc_util component was intended to be an internal implementation detail of shaderc.  @fjhenigman pulled out some common enums and visibility macros to be reused by the libshaderc_spvc library and put it in the libshader_util component, an entirely reasonable assumption.    

At the moment I think the preferred solution is  to pull out the libshaderc_util/common.h and .../visibility.h out to a shaderc/...    path.     Sadly (my fault) the "shaderc/..." hierarchy is overloaded for both truly generic things and also the functionality that wraps around the Glslang compiler flow.

**Comment by dneto0** [comment] 2019-01-29 00:43
For reference this is the offending commit: https://github.com/google/shaderc/commit/a0a4695765d8641576c3e34294145c345b50dbdc

**Comment by fjhenigman** [comment] 2019-01-29 01:45
Can you bug reporters test 0af5dc2a ?   I'm not sure exactly how you're using shaderc so while I think this will solve your problem it would be great if you can verify.

**Comment by Themaister** [comment] 2019-01-29 13:41
I can't seem to check out that commit hash. It doesn't exist after I pull.

**Comment by avih** [comment] 2019-01-29 14:20
> Can you bug reporters test [0af5dc2](https://github.com/google/shaderc/commit/0af5dc2a8a1443dc22afe926a90e19f00724bb12) ?

I'm also not seeing it on master.

The top commit on master ( https://github.com/google/shaderc/commits/master ) is 6ff17fe3 (Fix cmake build for libshaderc_spvc. (#554)).

With it applied (synced local to master), it still fails for me.

The newly (verified) installed`include/shaderc/shaderc.h` still has in it:

```c
#include "libshaderc_util/common.h"
#include "libshaderc_util/visibility.h"
```

But `libshaderc_util/` and its files are not installed inside `include/shaderc/`, and also nor directly at `include/`, or anywhere I could see.

**Comment by avih** [comment] 2019-01-29 14:31
The commit 0af5dc2a appears to be at the `install` branch at your (@fjhenigman ) fork: https://github.com/fjhenigman/shaderc/commits/install

After applying it:
```
curl https://github.com/fjhenigman/shaderc/commit/0af5dc2a8a1443dc22afe926a90e19f00724bb12.patch | git am
```

It indeed has `common.h` and `visibility.h` which are included from `shaderc.h`, all of those at `include/shaderc`.

With this fix, `mpv` can now use the resulting shaderc install, where before the fix it couldn't.

**Comment by dneto0** [comment] 2019-01-29 17:50
Thanks for verifying.   Because the proposed PR introduces new public header files, I want to split that common.h into two more focused files.

**Comment by fjhenigman** [comment] 2019-01-29 20:59
Wanted to leave this open until I was sure everyone was happy, but landing the change closed it.
Anyway, if that change doesn't fix everything, just reopen.

**Comment by Themaister** [comment] 2019-01-29 22:34
Still failing for me, not sure if it's related, but it's a different issue:

```
n file included from /home/maister/git/granite/third_party/shaderc/libshaderc/include/shaderc/shaderc.hpp:22,
                 from /home/maister/git/granite/compiler/compiler.cpp:24:
/home/maister/git/granite/third_party/shaderc/libshaderc/include/shaderc/shaderc.h:26:10: fatal error: shaderc/env.h: No such file or directory
 #include "shaderc/env.h"
```

**Comment by fjhenigman** [comment] 2019-01-29 22:52
I don't know what's wrong.  Can you give step by step instructions to reproduce your problem? Thanks.

**Comment by Themaister** [comment] 2019-01-29 23:02
```
git clone git://github.com/Themaister/Granite
cd Granite
git submodule update --remote
cd third_party/shaderc
git pull origin master
cd ../..
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
make -j8
```
On Linux, shoud repro on other OSes I guess.

**Comment by fjhenigman** [comment] 2019-01-30 01:30
I got it to work by adding this to your CMakeLists.txt :
target_include_directories(granite PUBLIC ${SHADERC_THIRD_PARTY_ROOT_DIR}/shaderc/libshaderc_util/include)

The other required shaderc include directory (shaderc/libshaderc/include) was there in the -I flags but I couldn't figure how it got there.  If someone can enlighten me, maybe we can see why that mechanism failed to add shaderc/libshaderc_util/include.

**Comment by dneto0** [comment] 2019-01-30 03:38
Ah.  The build-from-source flow is broken by putting the new headers under libshaderc_util.   That may have been my intuition about putting them in the libshaderc/include/shaderc hierarchy.   (See https://github.com/google/shaderc/pull/556#pullrequestreview-197350056 ) 
The existence of libshaderc_util is an implementation detail that others should not have to worry about.

**Comment by Themaister** [comment] 2019-01-30 08:34
@fjhenigman that workaround fixes it for me. I'll just use that until it's fixed on master.

**Comment by avih** [comment] 2019-01-30 09:22
> Ah. The build-from-source flow is broken by putting the new headers under libshaderc_util

I think the suggested workaround to add the include dir at 3rd party is a red herring WRT `libshaderc_util`.

The current top commit on master is e7a19107 . When building+installing it with cmake, It installs `shaderc.h`, `shaderc.hpp`, `env.h` and `visibility.h` into `include/shaderc/`. None of these files references files at  `libshaderc_util/`.

I get that the suggested workaround might work - but I don't see why and I don't quite understand why there's an issue in the first place. The installed files don't seem to reference anything which is not installed...

I think the issue could be as simple as `shaderc.hpp` including `shaderc.h` rather than `shaderc/shaderc.h` (`shaderc.h` itself does include files in `shaderc/...`).

With my use case (building mpv which uses the installed shaderc static lib) it works correctly. FWIW, mpv only includes `shaderc/shaderc.h`.

**Comment by fjhenigman** [comment] 2019-01-30 15:54
@Themaister 's issue is because he's not using an installed shaderc, but a shaderc source checkout as a subdirectory of his project.
@dneto0 shall I move those files where you suggested?

**Comment by dneto0** [comment] 2019-01-30 21:17
> @Themaister 's issue is because he's not using an installed shaderc, but a shaderc source checkout as a subdirectory of his project.

Agreed.  

> @dneto0 shall I move those files where you suggested?

Yes please. The project should be able to be built both ways: incorporation as subproject in CMake build, and from installed sources.  Moving the new files to the libshaderc/include/shaderc tree should solve both problems.

**Comment by dneto0** [comment] 2019-01-30 21:18
Other projects include the Shaderc tree and they should continue to work without having to adjust.

**Comment by fjhenigman** [comment] 2019-01-31 05:08
> @fjhenigman that workaround fixes it for me. I'll just use that until it's fixed on master.

You can try when ready.

**Comment by fjhenigman** [comment] 2019-03-22 17:54
I suspect this resolved.  If not please reopen.

**Closed by fjhenigman** 2019-03-22 17:54 UTC
